---
- name: Check if user has lingering enabled.
  ansible.builtin.command:
    cmd: "ls /var/lib/systemd/linger"
  changed_when: false
  register: linger

- name: Enable linger for user {{ mariadb_user }}
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ mariadb_user }}"
  changed_when: true
  when: "mariadb_user not in linger.stdout"

- name: Run tasks under user {{ mariadb_user }}.
  become: true
  become_user: "{{ mariadb_user }}"
  block:
    - name: Include app tasks.
      ansible.builtin.include_tasks: app.yml
