---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: mariadb
    box: rockylinux/9
    memory: 1024
    cpu: 1
provisioner:
  name: ansible
verifier:
  name: ansible
